ChaiToast/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from ChaiToast import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")), # This hot-reloads the page
    path('', views.landing, name='landing'),
    path('seller/', include('seller.urls')),
    path('user/', include('user.urls')),
    path('', views.landing, name='landing'),

]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

apps/seller/urls.py
from django.urls import path,include
from seller import views

urlpatterns = [
    path('', views.home, name="home"),
    path('loginseller/',views.loginseller,name ='loginseller'),
    path('signupseller/',views.signupseller,name ='signupseller'),
    path('signoutseller/',views.logoutseller,name ='logoutseller'),
]

apps/user/urls.py
from django.urls import path,include
from user import views
from .views import  add_to_cart, view_cart, remove_from_cart


from django.conf import settings
from django.conf.urls.static import static


app_name = 'cart'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('home/', views.home, name="home"),
    path('add_to_cart/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('cart/', view_cart, name='view_cart'),
    path('remove/<int:item_id>/', remove_from_cart, name='remove_from_cart'),
    path('loginuser',views.loginuser,name ='loginuser'),
    path('signupuser',views.signupuser,name ='signupuser'),
    path('logoutuser',views.logoutuser,name ='logoutuser'),
    path('contact',views.contact,name='contact'),
    path('about/', views.about_us, name='about'),

    




]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

apps/seller/models.py
from django.db import models

class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name

apps/user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings


# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='products/')
    def __str__(self):
        return self.name
class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} @ {self.quantity} x {self.product.name} - {self.date_added}'
    
class contact_info(models.Model):
    u_email = models.EmailField()
    u_message = models.CharField(max_length=200)
    def __str__(self):
        return self.u_email
    

ChaiToast/views.py
from django.shortcuts import render

# Create your views here.
def landing(request):
  return render(request, 'ChaiToast/landing.html')

apps/seller/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate,login,logout

# Create your views here.
def home(request):
    return render(request, 'seller/sellerhome.html')

def signupseller(request):
    if  request.method == 'GET':
        return render(request,'seller/signupseller.html',{'form': UserCreationForm()})
    else:
        a=request.POST.get('username')
        b=request.POST.get('password1')
        c=request.POST.get('password2')
        if b==c:
            #check whether user name is unique
            if (User.objects.filter(username = a)):
                return render(request, 'seller/signupseller.html',{'form': UserCreationForm(), 'error':'Username already exists Try again with different username'})
            else:
                user=User.objects.create_user(username = a, password =b)
                user.save()
                login(request,user)
                return redirect('/seller/')

        else:
            #password 1 and 2 do not match
            return render(request, 'seller/signupseller.html',{'form': UserCreationForm(),'error':'Password Mismatch Try Again'})


def loginseller(request):
    if request.method == 'GET':
        return render(request, 'seller/loginseller.html', {'form': AuthenticationForm()})
    else:
        a = request.POST.get('username')
        b = request.POST.get('password')
        user = authenticate(request, username=a, password=b)
        if user is None:
            return render(request, 'seller/loginseller.html', {'form': AuthenticationForm(), 'error': 'Invalid credentials'})
        else:
            login(request, user)
            return redirect('/seller/')  # Replace 'user_page' with the URL name of your user page

def logoutseller(request):
    if request.method == 'GET':
        logout(request)
        return redirect('/loginseller/')

apps/user/views.py
from django.shortcuts import render, redirect
from .models import Product, CartItem, contact_info
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required







# Create your views here.
@login_required(login_url='loginuser')
def home(request):
    return render(request, 'user/userhome.html')

def product_list(request):
    products = Product.objects.all()
    return render(request, 'user/userhome.html', {'products': products})

def view_cart(request):
    cart_items = CartItem.objects.filter(user=request.user)
    total_price = sum(item.product.price * item.quantity for item in cart_items)
    return render(request, 'user/cart.html', {'cart_items': cart_items, 'total_price': total_price})

def add_to_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    cart_item, created = CartItem.objects.get_or_create(product=product, 
                                                        user=request.user)
    cart_item.quantity += 1
    cart_item.save()
    return redirect('cart:view_cart')

def remove_from_cart(request, item_id):
    cart_item = CartItem.objects.get(id=item_id)
    cart_item.delete()
    return redirect('cart:view_cart')

def loginuser(request):
    if request.method == 'GET':
        return render(request, 'user/loginuser.html', {'form': AuthenticationForm()})
    else:
        a = request.POST.get('username')
        b = request.POST.get('password')
        user = authenticate(request, username=a, password=b)
        if user is None:
            return render(request, 'user/loginuser.html', {'form': AuthenticationForm(), 'error': 'Invalid credentials'})
        else:
            login(request, user)
            return redirect('/user/')  # Replace 'user_page' with the URL name of your user page
        

def signupuser(request):
    if  request.method == 'GET':
        return render(request,'user/signupuser.html',{'form': UserCreationForm()})
    else:
        a=request.POST.get('username')
        b=request.POST.get('password1')
        c=request.POST.get('password2')
        if b==c:
            #check whether user name is unique
            if (User.objects.filter(username = a)):
                return render(request, 'user/signupuser.html',{'form': UserCreationForm(), 'error':'Username already exists Try again with different username'})
            else:
                user=User.objects.create_user(username = a, password =b)
                user.save()
                login(request,user)
                return redirect('/user/')

        else:
            #password 1 and 2 do not match
            return render(request, 'user/signupuser.html',{'form': UserCreationForm(),'error':'Password Mismatch Try Again'})

def logoutuser(request):
    if request.method == 'GET':
        logout(request)
        return redirect('/user/')
    
def contact(request):   
    if request.method == 'GET':
        return render(request, 'user/contact.html')
    elif request.method == 'POST':
        email = request.POST.get('user_email')
        message = request.POST.get('message')
        x = contact_info(u_email=email, u_message=message)
        x.save()
        return render(request, 'user/contact.html', {'feedback': 'Your message has been recorded'})

def about_us(request):
    return render(request, 'user/about.html')

templates/user/cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shopping Cart</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <style>
        /* Global styles */
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4; /* Background color */
            color: #333;
        }
        /* Container styles */
        .container {
            max-width: 800px;
            margin: 20px auto;
            padding: 20px;
            background-color: #f4f4f4 ;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
        }
        /* Cart item styles */
        .product-list {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            list-style: none;
            padding: 0;
            margin: 0;
        }
        .product-item {
            border: 1px solid #ccc;
            border-radius: 10px;
            padding: 20px;
            background-color: #fff;
            transition: transform 0.3s ease;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.3);
        }
        .product-item:hover {
            transform: translateY(-5px);
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.2);
        }
        .product-item p {
            margin: 5px 0;
        }
        /* Button styles */
        .btn {
            display: inline-block;
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            text-decoration: none;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
            font-weight: bold;
            margin-right: 10px;
        }
        .btn:last-child {
            margin-right: 0;
        }
        .btn:hover {
            background-color: #0056b3;
        }
        /* Empty cart message */
        .empty-cart-msg {
            text-align: center;
            font-style: italic;
        }
        /* Total price */
        .total-price {
            margin-top: 20px;
            font-weight: bold;
            text-align: right;
        }
        /* Center the title */
        h1 {
            text-align: center;
            color: #007bff;
            margin-bottom: 20px;
        }
        /* Center align buttons */
        .btn-container {
            text-align: center;
            margin-top: 20px;
        }
        /* Quantity input */
        .quantity-input {
            width: 50px;
            text-align: center;
            padding: 8px;
            border: 1px solid #ccc;
            border-radius: 5px;
            margin: 0 5px;
        }
        /* Quantity buttons */
        .quantity-btn {
            padding: 4px 8px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
            font-size: 14px;
        }
        .quantity-btn:hover {
            background-color: #0056b3;
        }
        /* Quantity container */
        .quantity-container {
            display: flex;
            align-items: center;
            justify-content: center;
            margin-top: 10px;
        }
        /* Product name */
        .product-name {
            font-size: 18px;
            font-weight: bold;
            margin-bottom: 10px;
            text-align: center;
        }
        /* Price */
        .product-price {
            font-size: 16px;
            color: #777;
            margin-bottom: 10px;
            text-align: center;
        }
        /* Image */
        .product-image {
            width: 100%;
            border-radius: 10px;
            margin-bottom: 10px;
        }
        /* Remove button */
        .remove-btn-container {
            display: flex;
            justify-content: center;
            margin-top: 10px;
        }
        /* Custom styling for remove button */
        .remove-btn {
            background-color: #dc3545;
            margin-left: 10px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>ORDER CART <i class="fas fa-shopping-cart"></i></h1>
        <ul class="product-list">
            {% for item in cart_items %}
            <li class="product-item">
                {% comment %} <img src="{{ item.product.image_url }}" alt="{{ item.product.name }}" class="product-image"> {% endcomment %}
                <div class="product-details">
                    <p class="product-name">{{ item.product.name }}</p>
                    <p class="product-price">Rs. {{ item.product.price }}</p>
                    {% comment %} <div class="quantity-container">
                        <button class="quantity-btn btn" onclick="decreaseQuantity(this)"><i class="fas fa-minus"></i></button>
                        <input type="number" class="quantity-input" value="{{ item.quantity }}" min="1">
                        <button class="quantity-btn btn" onclick="increaseQuantity(this)"><i class="fas fa-plus"></i></button>
                    </div> {% endcomment %}
                    <div class="remove-btn-container">
                        <a href="{% url 'cart:remove_from_cart' item.id %}" class="btn remove-btn">Remove <i class="fas fa-trash"></i></a>
                    </div>
                </div>
            </li>
            {% empty %}
            <p class="empty-cart-msg">Your cart is empty.</p>
            {% endfor %}
        </ul>
        <p class="total-price"><h3>Total Price: Rs.{{ total_price }}</h3></p>
        <div class="btn-container">
            <a href="{% url 'cart:product_list' %}" class="btn continue-shopping-btn">Continue Ordering <i class="fas fa-arrow-right"></i></a>
            <br>
            <a href="" class="btn payment-btn" style="margin-top: 10px">Checkout <i class="fas fa-credit-card"></i></a>
        </div>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

templates/user/logoutuser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LOGOUT </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <div class="container mt-4 text-center">
        <h2 class="alert alert-success">Logout Form</h2>
        <form method="post" action="{% url 'logout' %}">
            {% csrf_token %}
            <button class="btn btn-primary" type="submit">Logout</button>
        </form>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

templates/user/userhome.html
{% extends "utils/base.html" %}

{% block title %}USER{% endblock %}

{% block body %}
 {% include 'utils/navbar.html' %}
<!-- Bootstrap CSS -->
<link href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet">

<!-- Bootstrap Bundle with Popper -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>
<!-- jQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<style>
    .card {
        border: 1px solid #ddd;
        border-radius: 10px;
        margin-bottom: 20px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);
    }

    .card-img-top {
        height: 200px; /* Set a fixed height for the images */
        object-fit: cover; /* Resize the images to cover the container */
        border-top-left-radius: 10px;
        border-top-right-radius: 10px;
    }

    .card-title {
        color: #333;
        font-weight: bold;
    }

    .card-text {
        color: #666;
    }

    .btn-primary {
        background-color: #007bff;
        border-color: #007bff;
    }

    .btn-primary:hover {
        background-color: #0056b3;
        border-color: #0056b3;
    }
</style>


<div class="container">
    {% comment %} <!--CAROUSEL STARTS HERE-->
    <div class="container-fluid p-0" style="margin-top: 100px; margin-bottom: 100px;">
        <div id="carouselExampleCaptions" class="carousel slide" style="margin-left: 50px;margin-right: 50px; margin-top: 30px; margin-bottom: 40px;">

            <div class="carousel-indicators">
                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"
                    aria-current="true" aria-label="Slide 1"></button>
                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"
                    aria-label="Slide 2"></button>
                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2"
                    aria-label="Slide 3"></button>
            </div>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="https://images.news18.com/ibnlive/uploads/2023/05/international-tea-day-2023.jpg"
                        class="d-block w-100" alt="..." style="border-radius: 20px;">
                    <div class="carousel-caption  d-md-block">
                        <h3>Enjoy the perfect combination of Masala Chai with crispy Samosa 😋</h3>
                        <!-- <p></p> -->
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="https://maayeka.com/wp-content/uploads/2013/10/bmathri-aa-1-of-1.jpg"
                        class="d-block w-100" alt="..." style="border-radius: 20px;">
                    <div class="carousel-caption  d-md-block">
                        <h3>Indulge in some Methi Mathi with your chai 😋</h3>
                        <!-- <p></p> -->
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="https://cdn.shopify.com/s/files/1/0528/5173/6769/files/TPS---1080-X-683-pxl---03-06-22--A1.jpg?v=1654254511"
                        class="d-block w-100" alt="..." style="border-radius: 20px;">
                    <div class="carousel-caption  d-md-block">
                        <h3>Masala Chai: A traditional Indian tea made by brewing black tea with aromatic spices and herbs</h3>
                        <!-- <p></p> -->
                    </div>
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions"
                data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions"
                data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    
    
    </div> {% endcomment %}
    
    <!-- <div class="container">
        <div class="row justify-content-center mt-2 text-center">
            <div class="col-md-6">
                <h2>Find Tea Sellers</h2>
                <p>Discover a variety of tea sellers available in your area.</p> -->
                <!-- Add code to display tea sellers -->
                <!-- Search box -->
                <!-- <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search for tea sellers" aria-label="Search" name="q">
                    <button class="btn btn-primary" type="submit">Search</button>
                </form>
            </div>
        </div>
    </div> -->
    
    {% comment %} <style>
         .carousel-item {
            position: relative;
            height: 100vh;
            /* Set a default height for large screens */
        }

        .carousel-item img {
            object-fit: cover;
            width: 100%;
            max-height: 100%;
            /* Set a max-height for the images */
        }

        .carousel-caption {
            position: absolute;
            bottom: 100px;
            left: 0;
            width: 100%;
            text-align: center;
            color: #fff;
            /* Text color */
            padding: 20px;
            /* Increased padding for better visibility */
            background-color: rgba(0, 0, 0, 0.5);
            /* Background color with some transparency */
            border-radius: 10px;
            /* Optional: Add border-radius for rounded corners */
            animation: slide-up 1s ease-out;
            /* Add animation for slide-up */
        }

        .carousel-caption h3 {
            margin: 0;
            /* Remove default margin for better appearance */
        }

        @media only screen and (max-width: 600px) {

            /* Media query for phones */
            #carouselExampleCaptions img {
                height: 700px;
                /* Set a different height for small screens */
            }

            .carousel-caption {
                position: absolute;
                bottom: 0;
                /* Adjust position to align with the bottom */
                width: 100%;
                top: 60%;
                text-align: center;
                color: #fff;
                /* Text color */
                padding: 10px;
                background-color: rgba(0, 0, 0, 0.2);
                /* More transparent background */
                border-radius: 10px;
                animation: slide-up 1s ease-out;
                /* Add animation for slide-up */
            }

            .carousel-item {
                height: 200px;
                /* Adjust height for small screens */
            }

            .carousel-control-prev,
            .carousel-control-next,
            .carousel-indicators {
                display: none !important;
            }
        }

        @media only screen and (min-width: 601px) and (max-width: 992px) {

            /* Media query for tablets */
            #carouselExampleCaptions img {
                height: 600px;
                /* Set a different height for tablets */
            }

            .carousel-caption {
                position: absolute;
                top: 80%;
                left: 50%;
                transform: translate(-50%, -50%);
                width: 80%;
                text-align: center;
                color: #fff;
                /* Text color */
                padding: 60px;
                background-color: rgba(0, 0, 0, 0.1);
                /* More transparent background */
                border-radius: 10px;
                animation: slide-up 1s ease-out;
                /* Add animation for slide-up */
            }

            .carousel-item {
                height: 300px;
                /* Adjust height for tablets */
            }

            .carousel-control-prev,
            .carousel-control-next,
            .carousel-indicators {
                display: none !important;
            }
        }

        @media only screen and (min-width: 992px) {

            /* Media query for laptops and larger screens */
            #carouselExampleCaptions img {
                height: 600px;
                /* Set a different height for large screens */
            }

            .carousel-caption {
                position: absolute;
                bottom: 100px;
                left: 0;
                width: 100%;
                text-align: center;
                color: #fff;
                /* Text color */
                padding: 20px;
                /* Increased padding for better visibility */
                background-color: rgba(0, 0, 0, 0.2);
                /* Background color with some transparency */
                border-radius: 10px;
                /* Optional: Add border-radius for rounded corners */
                animation: slide-up 1s ease-out;
                /* Add animation for slide-up */
            }

            .carousel-control-prev,
            .carousel-control-next,
            .carousel-indicators {
                display: none !important;
            }
        }

    </style>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
crossorigin="anonymous"></script>
<script>
// JavaScript to enable automatic sliding with a 3-second interval
document.addEventListener('DOMContentLoaded', function () {
    var myCarousel = new bootstrap.Carousel(document.getElementById('carouselExampleCaptions'), {
        interval: 2000, // Set the interval in milliseconds (3000ms = 3 seconds)
        ride: 'carousel'
    });
});
</script> {% endcomment %}






    <!--CAROUSEL ENDS HERE-->

    
<!-- FEATURED ITEMS STARTS HERE -->
<div class="row justify-content-center text-center">
    <div class="col-md-8">
        <h1 class="mt-5">HERE ARE WHAT WE OFFER</h1>
        <div class="row">
            {% for product in products %}
            <div class="col-md-4 mb-4">
                <div class="card">
                    <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <p class="card-text">{{ product.description }}</p>
                        <p class="card-text">Price: Rs.{{ product.price }}</p>
                        <a href="#" class="btn btn-primary mt-2">ORDER NOW</a>
                        <a href="#" class="btn btn-primary mt-2 add-to-cart-btn">Add to Cart</a>
                        <div class="quantity-controls mt-2" style="display: none;">
                            <button class="btn btn-sm btn-secondary decrement-btn">-</button>
                            <span class="quantity">1</span>
                            <button class="btn btn-sm btn-secondary increment-btn">+</button>
                        </div>
                        <a href="{% url 'cart:add_to_cart' product.id %}" class="btn btn-primary mt-2 go-to-cart-btn" style="display: none;">Go to Cart</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<!-- FEATURED ITEMS ENDS HERE -->

<script>
    document.addEventListener('DOMContentLoaded', function() {
        var addToCartButtons = document.querySelectorAll('.add-to-cart-btn');

        addToCartButtons.forEach(function(button) {
            button.addEventListener('click', function(event) {
                event.preventDefault();
                var cardBody = button.parentElement;
                var quantityControls = cardBody.querySelector('.quantity-controls');
                var goToCartBtn = cardBody.querySelector('.go-to-cart-btn');

                quantityControls.style.display = 'block';
                goToCartBtn.style.display = 'block';
                button.style.display = 'none';

                var cartIcon = document.getElementById('cart-icon'); // Get the cart icon

                // Add a class to the cart icon
                cartIcon.classList.add('item-added-to-cart');
            });
        });

        var decrementButtons = document.querySelectorAll('.decrement-btn');
        decrementButtons.forEach(function(button) {
            button.addEventListener('click', function() {
                var quantityElement = button.nextElementSibling;
                var quantity = parseInt(quantityElement.textContent);
                if (quantity > 1) {
                    quantityElement.textContent = quantity - 1;
                }
            });
        });

        var incrementButtons = document.querySelectorAll('.increment-btn');
        incrementButtons.forEach(function(button) {
            button.addEventListener('click', function() {
                var quantityElement = button.previousElementSibling;
                var quantity = parseInt(quantityElement.textContent);
                quantityElement.textContent = quantity + 1;
            });
        });
    });
</script>

</div>
{% endblock body %}

templates/utils/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} | TestProject</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <!--Bootstrap Styles CDN-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    {% block body %}{% endblock %}

    <!--Bootstrap Scripts CDN-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>